"""MedSyn Population Shift Engine — Cohort Intelligence (Person 2).

This module quantifies and visualizes the population shift between:
1. Source Real Data (what was observed in the clinic)
2. Target Specification (what was requested by the researcher)
3. Synthetic Output (what was actually generated by the model)

Key Responsibilities:
- Population Shift table construction (Pre-generation and Post-generation)
- Target vs Source divergence and extrapolation factor calculations
- Directionality (Overrepresented, Underrepresented, Aligned)
- Shift Plausibility and Risk Scoring (detecting extreme extrapolation on rare subsets)
- Drop-in support for Streamlit dashboard display
"""

from __future__ import annotations

import itertools
from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any, Dict, Iterable, List, Optional, Sequence, Union

import numpy as np
import pandas as pd

from feasibility import (
    CohortCondition,
    CohortRequest,
    evaluate_condition_mask,
    find_patient_identifier,
    validate_cohort_request,
)


# ---------------------------------------------------------------------------
# Shift Plausibility & Risk Metrics
# ---------------------------------------------------------------------------

def evaluate_shift_risk(
    source_pct: float,
    target_pct: float,
    source_count: int,
) -> Dict[str, Any]:
    """Evaluate whether a shift from source_pct to target_pct is plausible.

    Args:
        source_pct: Observed prevalence in source (0.0 to 100.0).
        target_pct: Desired prevalence in target cohort (0.0 to 100.0).
        source_count: Distinct source patients satisfying the condition.

    Returns:
        Dict with delta, ratio, severity, plausibility_score, and warning.
    """
    delta = round(target_pct - source_pct, 2)
    ratio = round(target_pct / max(source_pct, 0.01), 2)

    # Extreme case: source is zero or near-zero
    if source_count == 0:
        return {
            "delta": delta,
            "ratio": float("inf"),
            "severity": "Impossible (Zero Source Evidence)",
            "plausibility_score": 0.0,
            "warning": "No patients in source dataset satisfy this condition. Generator cannot learn this pattern.",
        }

    # Severe case: very low count (<10) with large magnification
    if source_count < 10 and ratio > 5.0:
        severity = "Extreme Extrapolation ⚠️"
        plausibility = max(10.0, 100.0 - (ratio * 8.0))
        warning = (
            f"Extreme magnification ({ratio:.1f}x) from only {source_count} patients. "
            "Generative model will either memorize those records (privacy risk) or produce mode collapse."
        )
    elif abs(delta) > 30.0 or ratio > 3.0:
        severity = "Significant Shift"
        plausibility = 50.0
        warning = f"Substantial population shift ({delta:+.1f}%). Inter-variable correlations may become distorted."
    elif abs(delta) > 15.0 or ratio > 1.5:
        severity = "Moderate Shift"
        plausibility = 75.0
        warning = "Moderate shift. Generally within the learning capacity of copula and neural synthesizers."
    else:
        severity = "Minimal Shift (Aligned)"
        plausibility = 95.0
        warning = "Target prevalence closely aligns with observed source evidence."

    return {
        "delta": delta,
        "ratio": ratio,
        "severity": severity,
        "plausibility_score": round(plausibility, 1),
        "warning": warning,
    }


# ---------------------------------------------------------------------------
# Population Shift Result Container
# ---------------------------------------------------------------------------

class PopulationShiftResult(Mapping):
    """Container for pre- and post-generation population shift analysis.

    Implements the Mapping interface and provides DataFrame export methods.
    """

    def __init__(self, data: Dict[str, Any]) -> None:
        self._data = data

    def __getitem__(self, key: str) -> Any:
        return self._data[key]

    def __iter__(self) -> Iterable[str]:
        return iter(self._data)

    def __len__(self) -> int:
        return len(self._data)

    def get(self, key: str, default: Any = None) -> Any:
        return self._data.get(key, default)

    @property
    def table(self) -> pd.DataFrame:
        """Return the complete population shift DataFrame."""
        return pd.DataFrame(self._data.get("rows", []))

    @property
    def has_generated(self) -> bool:
        """True if generated synthetic data was evaluated."""
        return bool(self._data.get("has_generated", False))

    @property
    def mean_absolute_shift(self) -> float:
        return float(self._data.get("mean_absolute_shift", 0.0))

    @property
    def max_shift(self) -> float:
        return float(self._data.get("max_shift", 0.0))

    @property
    def extrapolation_risk(self) -> str:
        return str(self._data.get("extrapolation_risk", "Low"))

    def to_dataframe(self) -> pd.DataFrame:
        return self.table

    def to_dict(self) -> Dict[str, Any]:
        return dict(self._data)

    def summary(self) -> str:
        """Generate a markdown report of the population shift."""
        lines = [
            "### Population Shift Summary",
            f"- **Mean Absolute Shift**: {self.mean_absolute_shift:.1f}%",
            f"- **Maximum Shift**: {self.max_shift:.1f}%",
            f"- **Extrapolation Risk**: {self.extrapolation_risk}",
            f"- **Post-Generation Evaluated**: {'Yes' if self.has_generated else 'No (Pre-generation planning)'}",
        ]
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Core Shift Table Calculation
# ---------------------------------------------------------------------------

def compute_population_shift(
    source_df: pd.DataFrame,
    request: Union[CohortRequest, Mapping[str, Any]],
    generated_df: Optional[pd.DataFrame] = None,
) -> PopulationShiftResult:
    """Compute the population shift table comparing Source, Target, and Generated data.

    Args:
        source_df: Real patient dataset.
        request: Cohort request specification.
        generated_df: Optional synthetic cohort DataFrame.

    Returns:
        PopulationShiftResult containing the formatted shift table,
        extrapolation diagnostics, and fidelity tracking.
    """
    if not isinstance(source_df, pd.DataFrame):
        raise TypeError("source_df must be a pandas DataFrame")

    cohort_req = validate_cohort_request(request, source_df)
    has_generated = generated_df is not None and isinstance(generated_df, pd.DataFrame) and not generated_df.empty

    source_patient_col = find_patient_identifier(source_df)
    source_total = source_df[source_patient_col].nunique() if source_patient_col else len(source_df)

    def source_count_fn(mask: pd.Series) -> int:
        if source_patient_col:
            return int(source_df.loc[mask, source_patient_col].nunique())
        return int(mask.sum())

    if has_generated:
        gen_patient_col = find_patient_identifier(generated_df)
        gen_total = generated_df[gen_patient_col].nunique() if gen_patient_col else len(generated_df)

        def gen_count_fn(mask: pd.Series) -> int:
            if gen_patient_col:
                return int(generated_df.loc[mask, gen_patient_col].nunique())
            return int(mask.sum())

    rows: List[Dict[str, Any]] = []
    source_masks: List[pd.Series] = []
    gen_masks: List[pd.Series] = []
    shifts: List[float] = []
    ratios: List[float] = []

    # 1. Individual Conditions
    for cond in cohort_req.conditions:
        s_mask = evaluate_condition_mask(source_df, cond)
        source_masks.append(s_mask)
        s_count = source_count_fn(s_mask)
        s_pct = round(s_count / max(source_total, 1) * 100, 2)
        t_pct = cond.target_pct

        risk = evaluate_shift_risk(s_pct, t_pct, s_count)
        shifts.append(abs(risk["delta"]))
        ratios.append(risk["ratio"])

        row: Dict[str, Any] = {
            "Variable": cond.variable,
            "Condition": cond.format_expression(),
            "Source count": s_count,
            "Source %": s_pct,
            "Target %": t_pct,
            "Target Shift (Δ)": f"{risk['delta']:+.1f}%",
            "Shift Ratio": f"{risk['ratio']:.1f}x" if risk["ratio"] != float("inf") else "∞",
            "Shift Severity": risk["severity"],
        }

        if has_generated:
            g_mask = evaluate_condition_mask(generated_df, cond)
            gen_masks.append(g_mask)
            g_count = gen_count_fn(g_mask)
            g_pct = round(g_count / max(gen_total, 1) * 100, 2)
            achieved_shift = round(g_pct - s_pct, 2)
            target_error = round(g_pct - t_pct, 2)

            if abs(target_error) <= 3.0:
                status = "Achieved (Within ±3%)"
            elif target_error < -3.0:
                status = f"Under-represented ({target_error:+.1f}%)"
            else:
                status = f"Over-represented ({target_error:+.1f}%)"

            row.update({
                "Generated count": g_count,
                "Generated %": g_pct,
                "Achieved Shift (Δ)": f"{achieved_shift:+.1f}%",
                "Target Error (Δ)": f"{target_error:+.1f}%",
                "Target Status": status,
            })

        rows.append(row)

    # 2. Joint Combination (All conditions combined)
    if source_masks:
        joint_s_mask = np.logical_and.reduce(source_masks)
        joint_s_count = source_count_fn(joint_s_mask)
        joint_s_pct = round(joint_s_count / max(source_total, 1) * 100, 2)
    else:
        joint_s_count = source_total
        joint_s_pct = 100.0

    combo_order = len(cohort_req.conditions)
    combo_label = (
        "Single condition" if combo_order == 1
        else "2-way combo" if combo_order == 2
        else "Triple combo" if combo_order == 3
        else f"{combo_order}-way combination"
    )

    # Target percentage for joint combo: if user specified metadata or lowest target
    # In clinical requests, joint prevalence is often the primary target or product of targets
    # Let's derive a sensible joint target percentage:
    joint_target_pct = (
        cohort_req.metadata.get("joint_target_pct")
        if cohort_req.metadata and "joint_target_pct" in cohort_req.metadata
        else min((c.target_pct for c in cohort_req.conditions), default=0.0)
    )

    joint_risk = evaluate_shift_risk(joint_s_pct, joint_target_pct, joint_s_count)
    shifts.append(abs(joint_risk["delta"]))
    ratios.append(joint_risk["ratio"])

    joint_row: Dict[str, Any] = {
        "Variable": "Combined (All Conditions)",
        "Condition": f"{combo_label} (Intersection)",
        "Source count": joint_s_count,
        "Source %": joint_s_pct,
        "Target %": joint_target_pct,
        "Target Shift (Δ)": f"{joint_risk['delta']:+.1f}%",
        "Shift Ratio": f"{joint_risk['ratio']:.1f}x" if joint_risk["ratio"] != float("inf") else "∞",
        "Shift Severity": joint_risk["severity"],
    }

    if has_generated:
        if gen_masks:
            joint_g_mask = np.logical_and.reduce(gen_masks)
            joint_g_count = gen_count_fn(joint_g_mask)
            joint_g_pct = round(joint_g_count / max(gen_total, 1) * 100, 2)
        else:
            joint_g_count = gen_total
            joint_g_pct = 100.0

        joint_achieved_shift = round(joint_g_pct - joint_s_pct, 2)
        joint_target_error = round(joint_g_pct - joint_target_pct, 2)

        if abs(joint_target_error) <= 3.0:
            status = "Achieved (Within ±3%)"
        elif joint_target_error < -3.0:
            status = f"Under-represented ({joint_target_error:+.1f}%)"
        else:
            status = f"Over-represented ({joint_target_error:+.1f}%)"

        joint_row.update({
            "Generated count": joint_g_count,
            "Generated %": joint_g_pct,
            "Achieved Shift (Δ)": f"{joint_achieved_shift:+.1f}%",
            "Target Error (Δ)": f"{joint_target_error:+.1f}%",
            "Target Status": status,
        })

    rows.append(joint_row)

    # 3. Overall Extrapolation Risk Calculation
    max_shift_val = max(shifts) if shifts else 0.0
    mean_shift_val = round(sum(shifts) / max(len(shifts), 1), 2)
    max_ratio_val = max((r for r in ratios if r != float("inf")), default=1.0)

    if joint_s_count < 10 and max_ratio_val > 5.0:
        extrapolation_risk = "Extreme Extrapolation ⚠️"
    elif max_shift_val > 35.0 or max_ratio_val > 3.0:
        extrapolation_risk = "High"
    elif max_shift_val > 15.0 or max_ratio_val > 1.5:
        extrapolation_risk = "Moderate"
    else:
        extrapolation_risk = "Low"

    payload: Dict[str, Any] = {
        "rows": rows,
        "has_generated": has_generated,
        "mean_absolute_shift": mean_shift_val,
        "max_shift": max_shift_val,
        "max_ratio": max_ratio_val,
        "extrapolation_risk": extrapolation_risk,
        "joint_source_count": joint_s_count,
        "joint_source_pct": joint_s_pct,
        "joint_target_pct": joint_target_pct,
    }

    return PopulationShiftResult(payload)


# ---------------------------------------------------------------------------
# Streamlit & Export Formatting
# ---------------------------------------------------------------------------

def format_population_shift_table(
    shift_result: Union[PopulationShiftResult, pd.DataFrame, Mapping[str, Any]],
) -> pd.DataFrame:
    """Return a styled, display-ready pandas DataFrame for the Streamlit UI."""
    if isinstance(shift_result, PopulationShiftResult):
        df = shift_result.to_dataframe()
    elif isinstance(shift_result, pd.DataFrame):
        df = shift_result.copy()
    elif isinstance(shift_result, Mapping) and "rows" in shift_result:
        df = pd.DataFrame(shift_result["rows"])
    else:
        df = pd.DataFrame(shift_result)

    return df


def actual_proportions(
    generated: pd.DataFrame,
    request: Union[CohortRequest, Mapping[str, Any]],
) -> pd.DataFrame:
    """Drop-in enhancement for app.py's _actual_proportions function.

    Returns a clean comparison DataFrame with Variable, Source Target %,
    Generated %, Deviation (Δ), and Achievement Status.
    """
    if not isinstance(generated, pd.DataFrame) or generated.empty:
        return pd.DataFrame()

    if isinstance(request, CohortRequest):
        conditions = request.conditions
    elif isinstance(request, Mapping):
        conditions = [CohortCondition.from_dict(c) for c in request.get("conditions", [])]
    else:
        return pd.DataFrame()

    gen_patient_col = find_patient_identifier(generated)
    total_gen = generated[gen_patient_col].nunique() if gen_patient_col else len(generated)

    rows = []
    for cond in conditions:
        if cond.variable not in generated.columns:
            actual = None
            diff = None
            status = "Missing Variable"
        else:
            mask = evaluate_condition_mask(generated, cond)
            if gen_patient_col:
                count = int(generated.loc[mask, gen_patient_col].nunique())
            else:
                count = int(mask.sum())
            actual = round(count / max(total_gen, 1) * 100, 2)
            deviation = round(actual - cond.target_pct, 2)
            diff = f"{deviation:+.1f}%"
            if abs(deviation) <= 3.0:
                status = "Achieved"
            elif deviation < -3.0:
                status = "Under-target"
            else:
                status = "Over-target"

        rows.append({
            "Variable": cond.variable,
            "Source target %": cond.target_pct,
            "Generated %": actual,
            "Deviation (Δ)": diff,
            "Status": status,
        })

    return pd.DataFrame(rows)
